services:
  ldns:
    build:
      target: development
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development #the app will spin up the target env variables
    env_file:
      - .env.dev
    ports:
      - 8087:8087
    user: 'appuser:appgroup'
    volumes:
      - ./src:/usr/app/src/
      # - ./node_modules:/usr/app/node_modules

  sql-db:
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=LDNS
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cache:
    ports:
      - 6379:6379
    volumes:
      - cache_data:/data

volumes:
  postgres_data: #/var/lib/docker/volumes/postgres_data/_data
  cache_data: #/var/lib/docker/volumes/cache_data/_data
