services:
  ldns:    
    depends_on:
      - sql-db

  sql-db:
    image: postgres:latest
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=academia-sync
    volumes:
      - ./local/postgres:/var/lib/postgresql/data
