services:
  server:
    build:
      target: final
      args:
        - NODE_ENV=prod
    environment:
      - NODE_ENV=prod #the app will spin up the target env variables
    env_file:
      - .env.prod
    ports:
      - 8089:8089
    user: 'appuser:appgroup'
    volumes:
      - ./src:/usr/app/src/
      - ./certs:/usr/app/certs

  sql-db:
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=LDSN
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cache:
    ports:
      - 6379:6379
    volumes:
      - cache_data:/data

volumes:
  postgres_data: #/var/lib/docker/volumes/postgres_data/_data
  cache_data: #/var/lib/docker/volumes/cache_data/_data
