services:
  ldns:
    build:
      target: development
      args:
        - NODE_ENV=dev
    environment:
      - NODE_ENV=dev #the app will spin up the target env variables
    env_file:
      - .env.dev
    ports:
      - 8087:8087
      - 8088:8088
    user: 'appuser:appgroup'
    volumes:
      - ./src:/usr/app/src/
      # - ./node_modules:/usr/app/node_modules

  sql-db:
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=LDNS
    volumes:
      - postgres_data:/var/lib/postgresql/data

  no-sql-db:
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb

  no-sql-db-client:
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: no-sql-db
      ME_CONFIG_MONGODB_PORT: '27017'
    ports:
      - '8081:8081'

  cache:
    ports:
      - 6379:6379
    volumes:
      - cache_data:/data

volumes:
  postgres_data: #/var/lib/docker/volumes/postgres_data/_data
  cache_data: #/var/lib/docker/volumes/cache_data/_data
  mongo_data: #/var/lib/docker/volumes/mongo_data/_data
  mongo_config: #/var/lib/docker/volumes/mongo_config/_data
