services:
  ldns:
    build:
      target: development
      args:
        - NODE_ENV=dev
    environment:
      - NODE_ENV=dev
    ports:
      - 8087:8087
    volumes:
      - ./src:/usr/app/src/
      - /node_modules
      - /.logs
