name: cd-workflow

on:
  workflow_run:
    workflows: ['ci-workflow']
    types: [completed]
    branches:
      - main
      - development
  workflow_dispatch:

jobs:
  setup: #The workflow must contain at least one job with no dependencies.
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: echo "Setting up deployment..."

  deploy:
    runs-on: ubuntu-latest
    needs: setup
    env:
      SSH_PASS: ${{ secrets.SSH_PASS }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}
      DOCKER_IMAGE_TAG: ${{ secrets.DOCKER_IMAGE_TAG }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts

      - name: Verify SSH Connectivity
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST 'echo "SSH Connection Successful"'

      - name: Deploy to Server
        run: |
          # Use SSH to connect to the remote server
          ssh -T -o StrictHostKeyChecking=no -o BatchMode=yes $SSH_USER@$SSH_HOST << 'EOF'
          
            # Navigate to the directory where the compose file is located
            cd app/server-networks || { echo "Failed to navigate to directory"; exit 1; }
            
            # Pull the new Docker image
            docker pull iscoadms/ldns-server:latest || { echo "Failed to pull Docker image"; exit 1; }
            
            # Stop and remove the existing containers
            ./stop_containers.sh || { echo "Failed to stop containers"; exit 1; }
            
            # Start the containers with the new image
            ./start_containers.sh || { echo "Failed to start containers"; exit 1; }
            
          EOF
