name: cd-workflow

on:
  workflow_run:
    workflows: ['ci-workflow']
    types: [completed]
    branches:
      - main
      - development
  workflow_dispatch:

jobs:
  setup: #The workflow must contain at least one job with no dependencies.
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: echo "Setting up deployment..."

  deploy:
    runs-on: ubuntu-latest
    needs: setup
    env:
      SSH_PASS: ${{ secrets.SSH_PASS }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts

      - name: Verify SSH Connectivity
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST 'echo "SSH Connection Successful"'

      - name: Deploy to Server
        run: |
          # Use sshpass to handle SSH password authentication
          sshpass -p "$SSH_PASS" ssh -t -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
            
            # Navigate to the directory where the compose file is located
            cd /app

            # Run Docker commands with sudo
            echo "$SSH_PASS" | sudo -S bash -c "docker-compose -f compose.yml pull && \
                                                 docker-compose -f compose.yml down -v || true && \
                                                 docker-compose -f compose.yml up -d --build"
          EOF
